from datetime import UTC, datetime

from app.schemas import Rule, RuleCondition


def builtin_rules() -> list[Rule]:
    now = datetime.now(UTC)
    return [
        Rule(
            rule_id="RULE_PUBLIC_BUCKET",
            name="Public Bucket",
            template_key="public_exposure",
            resource_type="bucket",
            conditions=[RuleCondition(field="config.public_access", operator="==", value=True)],
            severity_base="high",
            escalate_in_prod=True,
            rule_confidence=0.98,
            category="security",
            issue_type="public_bucket",
            required_reviewers=["security", "devops"],
            evidence_fields=["environment", "project_id", "owner_team"],
            remediation_action_key="restrict_public_access",
            remediation_destructive=False,
            agent_keys=["security", "workflow", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_IDLE_VM",
            name="Idle VM",
            template_key="idle_resource",
            resource_type="vm",
            conditions=[
                RuleCondition(field="metrics.avg_cpu_percent_7d", operator="<=", value=10),
                RuleCondition(field="metrics.network_in_mb_7d", operator="<=", value=100),
                RuleCondition(field="metrics.network_out_mb_7d", operator="<=", value=100),
            ],
            severity_base="medium",
            escalate_in_prod=True,
            rule_confidence=0.9,
            category="cost",
            issue_type="idle_vm",
            required_reviewers=["devops", "application_owner"],
            evidence_fields=["cost.monthly_usd", "config.application_id"],
            remediation_action_key="stop_vm",
            remediation_destructive=True,
            agent_keys=["cost", "energy", "workflow"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_UNUSED_STORAGE",
            name="Unused Storage",
            template_key="unused_resource",
            resource_type="storage",
            conditions=[
                RuleCondition(field="config.attached", operator="==", value=False),
                RuleCondition(field="metrics.read_ops_30d", operator="==", value=0),
                RuleCondition(field="metrics.write_ops_30d", operator="==", value=0),
            ],
            severity_base="medium",
            escalate_in_prod=False,
            rule_confidence=0.88,
            category="cost",
            issue_type="unused_storage",
            required_reviewers=["devops", "project_owner", "compliance"],
            evidence_fields=["cost.monthly_usd", "config.contains_sensitive_data"],
            remediation_action_key="delete_storage",
            remediation_destructive=True,
            agent_keys=["cost", "energy", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_UNENCRYPTED_DATABASE",
            name="Unencrypted Database",
            template_key="unencrypted_data",
            resource_type="database",
            conditions=[RuleCondition(field="config.encrypted", operator="==", value=False)],
            severity_base="high",
            escalate_in_prod=True,
            rule_confidence=0.97,
            category="security",
            issue_type="unencrypted_database",
            required_reviewers=["security", "devops", "application_owner", "dba"],
            evidence_fields=["environment", "config.engine", "config.application_id"],
            remediation_action_key="plan_encryption",
            remediation_destructive=False,
            agent_keys=["security", "workflow", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_FAILED_LOGIN",
            name="Failed Console Login",
            source_type="cloud_event",
            template_key="failed_login",
            resource_type="identity",
            conditions=[
                RuleCondition(field="config.action", operator="==", value="ConsoleLogin"),
                RuleCondition(field="config.status", operator="!=", value="Success"),
            ],
            severity_base="high",
            escalate_in_prod=False,
            rule_confidence=0.86,
            category="security",
            issue_type="failed_login",
            required_reviewers=["security", "audit"],
            evidence_fields=[
                "config.actor_id",
                "config.actor_type",
                "config.ip_address",
                "config.event_type",
                "config.source_id",
            ],
            remediation_action_key="review_identity_access",
            remediation_destructive=False,
            agent_keys=["security", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_IAM_CHANGE",
            name="IAM Policy Change",
            source_type="cloud_event",
            template_key="iam_change",
            resource_type="identity",
            conditions=[
                RuleCondition(
                    field="config.action",
                    operator="in",
                    value=["AttachRolePolicy", "PutRolePolicy", "CreatePolicy", "CreateAccessKey"],
                ),
                RuleCondition(field="config.status", operator="==", value="Success"),
            ],
            severity_base="high",
            escalate_in_prod=False,
            rule_confidence=0.88,
            category="security",
            issue_type="iam_policy_change",
            required_reviewers=["security", "devops", "audit"],
            evidence_fields=["config.actor_id", "config.action", "config.event_type", "config.source_id"],
            remediation_action_key="review_iam_change",
            remediation_destructive=False,
            agent_keys=["security", "workflow", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_FIREWALL_INGRESS_CHANGE",
            name="Firewall Ingress Change",
            source_type="cloud_event",
            template_key="firewall_ingress",
            resource_type="network",
            conditions=[
                RuleCondition(field="config.action", operator="==", value="AuthorizeSecurityGroupIngress"),
                RuleCondition(field="config.status", operator="==", value="Success"),
            ],
            severity_base="high",
            escalate_in_prod=False,
            rule_confidence=0.9,
            category="security",
            issue_type="firewall_ingress_change",
            required_reviewers=["security", "devops"],
            evidence_fields=["config.actor_id", "config.ip_address", "config.event_type", "config.source_id"],
            remediation_action_key="review_firewall_change",
            remediation_destructive=False,
            agent_keys=["security", "workflow", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_BUCKET_POLICY_CHANGE",
            name="Bucket Policy Change",
            source_type="cloud_event",
            template_key="bucket_policy_change",
            resource_type="bucket",
            conditions=[
                RuleCondition(field="config.action", operator="==", value="PutBucketPolicy"),
                RuleCondition(field="config.status", operator="==", value="Success"),
            ],
            severity_base="high",
            escalate_in_prod=False,
            rule_confidence=0.9,
            category="security",
            issue_type="bucket_policy_change",
            required_reviewers=["security", "devops"],
            evidence_fields=["config.actor_id", "config.action", "config.source_id"],
            remediation_action_key="review_bucket_policy",
            remediation_destructive=False,
            agent_keys=["security", "workflow", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_AUDIT_LOGGING_CHANGE",
            name="Audit Logging Change",
            source_type="cloud_event",
            template_key="audit_logging_change",
            resource_type="audit",
            conditions=[
                RuleCondition(
                    field="config.action",
                    operator="in",
                    value=["StopLogging", "DeleteTrail", "UpdateTrail"],
                ),
            ],
            severity_base="critical",
            escalate_in_prod=False,
            rule_confidence=0.92,
            category="security",
            issue_type="audit_logging_change",
            required_reviewers=["security", "compliance"],
            evidence_fields=["config.actor_id", "config.status", "config.event_type", "config.source_id"],
            remediation_action_key="review_audit_logging",
            remediation_destructive=False,
            agent_keys=["security", "audit"],
            created_at=now,
        ),
        Rule(
            rule_id="RULE_DATABASE_CHANGE",
            name="Database Change",
            source_type="cloud_event",
            template_key="database_change",
            resource_type="database",
            conditions=[
                RuleCondition(
                    field="config.action",
                    operator="in",
                    value=["CreateDBInstance", "ModifyDBInstance", "DeleteDBInstance"],
                ),
                RuleCondition(field="config.status", operator="==", value="Success"),
            ],
            severity_base="medium",
            escalate_in_prod=True,
            rule_confidence=0.84,
            category="security",
            issue_type="database_change",
            required_reviewers=["security", "devops", "dba"],
            evidence_fields=["config.actor_id", "config.action", "config.event_type", "config.source_id"],
            remediation_action_key="review_database_change",
            remediation_destructive=False,
            agent_keys=["security", "workflow", "audit"],
            created_at=now,
        ),
    ]
