from datetime import UTC, datetime

from app.schemas import Rule, RuleCondition


def builtin_rules() -> list[Rule]:
    now = datetime.now(UTC)
    return [
        Rule(
            rule_id="RULE_PUBLIC_BUCKET",
            name="Public Bucket",
            template_key="public_exposure",
            resource_type="bucket",
            conditions=[RuleCondition(field="config.public_access", operator="==", value=True)],
            severity_base="high",
            escalate_in_prod=True,
            rule_confidence=0.98,
            category="security",
            issue_type="public_bucket",
            required_reviewers=["security", "devops"],
            evidence_fields=["environment", "project_id", "owner_team"],
            remediation_action_key="restrict_public_access",
            remediation_destructive=False,
            created_at=now,
        ),
        Rule(
            rule_id="RULE_IDLE_VM",
            name="Idle VM",
            template_key="idle_resource",
            resource_type="vm",
            conditions=[
                RuleCondition(field="metrics.avg_cpu_percent_7d", operator="<=", value=10),
                RuleCondition(field="metrics.network_in_mb_7d", operator="<=", value=100),
                RuleCondition(field="metrics.network_out_mb_7d", operator="<=", value=100),
            ],
            severity_base="medium",
            escalate_in_prod=True,
            rule_confidence=0.9,
            category="cost",
            issue_type="idle_vm",
            required_reviewers=["devops", "application_owner"],
            evidence_fields=["cost.monthly_usd", "config.application_id"],
            remediation_action_key="stop_vm",
            remediation_destructive=True,
            created_at=now,
        ),
        Rule(
            rule_id="RULE_UNUSED_STORAGE",
            name="Unused Storage",
            template_key="unused_resource",
            resource_type="storage",
            conditions=[
                RuleCondition(field="config.attached", operator="==", value=False),
                RuleCondition(field="metrics.read_ops_30d", operator="==", value=0),
                RuleCondition(field="metrics.write_ops_30d", operator="==", value=0),
            ],
            severity_base="medium",
            escalate_in_prod=False,
            rule_confidence=0.88,
            category="cost",
            issue_type="unused_storage",
            required_reviewers=["devops", "project_owner", "compliance"],
            evidence_fields=["cost.monthly_usd", "config.contains_sensitive_data"],
            remediation_action_key="delete_storage",
            remediation_destructive=True,
            created_at=now,
        ),
        Rule(
            rule_id="RULE_UNENCRYPTED_DATABASE",
            name="Unencrypted Database",
            template_key="unencrypted_data",
            resource_type="database",
            conditions=[RuleCondition(field="config.encrypted", operator="==", value=False)],
            severity_base="high",
            escalate_in_prod=True,
            rule_confidence=0.97,
            category="security",
            issue_type="unencrypted_database",
            required_reviewers=["security", "devops", "application_owner", "dba"],
            evidence_fields=["environment", "config.engine", "config.application_id"],
            remediation_action_key="plan_encryption",
            remediation_destructive=False,
            created_at=now,
        ),
    ]
