from app.schemas import RuleCondition, RuleTemplate

RULE_TEMPLATES: list[RuleTemplate] = [
    RuleTemplate(
        template_key="public_exposure",
        name="Public Exposure",
        description="Flag a resource that is reachable from the public internet.",
        resource_type="bucket",
        conditions=[RuleCondition(field="config.public_access", operator="==", value=True)],
        severity_base="high",
        escalate_in_prod=True,
        rule_confidence=0.98,
        category="security",
        issue_type="public_bucket",
        required_reviewers=["security", "devops"],
        evidence_fields=["environment", "project_id", "owner_team"],
        remediation_action_key="restrict_public_access",
        remediation_destructive=False,
    ),
    RuleTemplate(
        template_key="idle_resource",
        name="Idle Resource",
        description="Flag a compute resource with sustained low utilisation.",
        resource_type="vm",
        conditions=[RuleCondition(field="metrics.avg_cpu_percent_7d", operator="<=", value=10)],
        severity_base="medium",
        escalate_in_prod=True,
        rule_confidence=0.9,
        category="cost",
        issue_type="idle_vm",
        required_reviewers=["devops", "application_owner"],
        evidence_fields=["cost.monthly_usd", "config.application_id"],
        remediation_action_key="stop_vm",
        remediation_destructive=True,
    ),
    RuleTemplate(
        template_key="unused_resource",
        name="Unused Resource",
        description="Flag an unattached/idle storage volume with no recent I/O.",
        resource_type="storage",
        conditions=[
            RuleCondition(field="config.attached", operator="==", value=False),
            RuleCondition(field="metrics.read_ops_30d", operator="==", value=0),
        ],
        severity_base="medium",
        escalate_in_prod=False,
        rule_confidence=0.88,
        category="cost",
        issue_type="unused_storage",
        required_reviewers=["devops", "project_owner"],
        evidence_fields=["cost.monthly_usd", "config.contains_sensitive_data"],
        remediation_action_key="delete_storage",
        remediation_destructive=True,
    ),
    RuleTemplate(
        template_key="unencrypted_data",
        name="Unencrypted Data",
        description="Flag a datastore that is not encrypted at rest.",
        resource_type="database",
        conditions=[RuleCondition(field="config.encrypted", operator="==", value=False)],
        severity_base="high",
        escalate_in_prod=True,
        rule_confidence=0.97,
        category="security",
        issue_type="unencrypted_database",
        required_reviewers=["security", "devops", "dba"],
        evidence_fields=["environment", "config.engine"],
        remediation_action_key="plan_encryption",
        remediation_destructive=False,
    ),
    RuleTemplate(
        template_key="forbidden_config_value",
        name="Forbidden Config Value",
        description="Flag when a config field equals a value you have banned.",
        resource_type="database",
        conditions=[RuleCondition(field="config.engine", operator="==", value="mysql")],
        severity_base="medium",
        escalate_in_prod=False,
        rule_confidence=0.8,
        category="security",
        issue_type="forbidden_config",
        required_reviewers=["security"],
        evidence_fields=["environment"],
        remediation_action_key="tag_resource",
        remediation_destructive=False,
    ),
    RuleTemplate(
        template_key="threshold_breach",
        name="Threshold Breach",
        description="Flag when a numeric metric crosses a threshold you set.",
        resource_type="vm",
        conditions=[RuleCondition(field="metrics.avg_cpu_percent_7d", operator=">=", value=90)],
        severity_base="medium",
        escalate_in_prod=True,
        rule_confidence=0.75,
        category="cost",
        issue_type="threshold_breach",
        required_reviewers=["devops"],
        evidence_fields=["cost.monthly_usd"],
        remediation_action_key="tag_resource",
        remediation_destructive=False,
    ),
    RuleTemplate(
        template_key="sensitive_data_exposure",
        name="Sensitive-Data Exposure",
        description="Flag a sensitive-tagged resource that is also exposed.",
        resource_type="storage",
        conditions=[
            RuleCondition(field="config.contains_sensitive_data", operator="==", value=True),
            RuleCondition(field="config.attached", operator="==", value=False),
        ],
        severity_base="high",
        escalate_in_prod=True,
        rule_confidence=0.85,
        category="security",
        issue_type="sensitive_exposure",
        required_reviewers=["security", "compliance"],
        evidence_fields=["owner_team", "project_id"],
        remediation_action_key="snapshot_then_flag",
        remediation_destructive=False,
    ),
    RuleTemplate(
        template_key="custom",
        name="Custom Rule",
        description="Start from scratch with your own conditions.",
        resource_type="vm",
        conditions=[],
        severity_base="medium",
        escalate_in_prod=False,
        rule_confidence=0.8,
        category="security",
        issue_type="custom_finding",
        required_reviewers=["devops"],
        evidence_fields=[],
        remediation_action_key="tag_resource",
        remediation_destructive=False,
    ),
]


def get_templates() -> list[RuleTemplate]:
    return RULE_TEMPLATES
